spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-jpa-workshop
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

logging:
  level:
    root: error
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.cobi.querydsl: debug
